#!/usr/bin/env bash
# find-candidates.sh - enumerate source files eligible for comment stripping.
#
# Usage:
#   find-candidates.sh [root] [-- ext1 ext2 ...]
#
# Honours .gitignore when the root is a git work tree. Excludes dependency
# directories, build output, lockfiles, minified bundles, and files carrying a
# generated-code marker. Prints one path per line, relative to root.

set -uo pipefail

ROOT="."
if [ "${1:-}" != "" ] && [ "${1:-}" != "--" ]; then
  ROOT="$1"
  shift
fi
[ "${1:-}" = "--" ] && shift

DEFAULT_EXTS="c cc cpp cxx h hh hpp cs go java kt kts scala swift rs rb php py pyi sh bash zsh sql js jsx mjs cjs ts tsx mts cts vue svelte astro css scss sass less lua pl pm r dart ex exs erl hs m mm ejs hbs handlebars html htm"
EXTS="${*:-$DEFAULT_EXTS}"

EXCLUDE_DIR_RE='(^|/)(node_modules|bower_components|vendor|third_party|\.git|\.hg|\.svn|dist|build|out|target|bin|obj|coverage|__pycache__|\.venv|venv|\.tox|\.next|\.nuxt|\.svelte-kit|\.output|\.cache|\.gradle|\.idea|\.vscode|Pods|DerivedData|site-packages|migrations/__pycache__)(/|$)'
EXCLUDE_FILE_RE='(\.min\.(js|css|mjs)|\.bundle\.js|\.pack\.js|-lock\.json|\.lock|\.map|\.snap|\.pb\.go|_pb2\.py|_pb2_grpc\.py|\.g\.dart|\.freezed\.dart|\.generated\.[a-z]+|\.designer\.cs|\.feature\.[a-z]+)$'
GENERATED_RE='@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated|This file was automatically generated'

cd "$ROOT" 2>/dev/null || { echo "find-candidates: cannot cd into $ROOT" >&2; exit 2; }

list_files() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # tracked + untracked-but-not-ignored, NUL separated
    git ls-files -z --cached --others --exclude-standard
  else
    find . -type f -print0
  fi
}

ext_match() {
  local f="$1" e
  for e in $EXTS; do
    case "$f" in *."$e") return 0;; esac
  done
  return 1
}

while IFS= read -r -d '' f; do
  f="${f#./}"
  ext_match "$f" || continue
  printf '%s' "$f" | grep -Eq "$EXCLUDE_DIR_RE" && continue
  printf '%s' "$f" | grep -Eq "$EXCLUDE_FILE_RE" && continue
  [ -s "$f" ] || continue

  # generated-code marker in the first 5 lines
  head -n 5 "$f" 2>/dev/null | grep -Eqi "$GENERATED_RE" && continue

  # minified heuristic: any line longer than 500 chars
  if awk 'length($0) > 500 { found=1; exit } END { exit !found }' "$f" 2>/dev/null; then
    echo "find-candidates: skipping (long lines, likely minified): $f" >&2
    continue
  fi

  printf '%s\n' "$f"
done < <(list_files) | sort -u
