<?php
// Dependencies for editor.js (normally generated by @wordpress/scripts; hand-written here because there is no build step).
return array(
	'dependencies' => array( 'wp-blocks', 'wp-element', 'wp-block-editor', 'wp-server-side-render' ),
	'version'      => '1.0.0',
);
